#!/usr/bin/env node
// Personalize this template for a new project.
// Usage: pnpm run init <project-name> [--reset-git]
//
// What it does:
//  - Renames `name` in package.json to <project-name>.
//  - Replaces every standalone "albo" brand token (case-preserving) across all
//    tracked files with the new brand (kebab slug for lowercase `albo`,
//    capitalized display for `Albo`). Files are discovered dynamically, so a
//    newly-added file never gets missed by a stale list.
//  - Renders a clean product README from README.product.md (dropping the
//    "this is a template" framing) and de-templatizes CLAUDE.md.
//  - Asserts ZERO residual brand token remains, failing loudly otherwise.
//  - Optionally resets git history to a single "chore: scaffold" commit
//    (only if --reset-git is passed).
//
// The upstream identity `albo-ouvre-boite` / `Albo-Club` is deliberately
// PRESERVED everywhere — the `template` git remote and the skills sync both
// point at it, so rewriting it would break the update channel.
//
// Run from the project root. Idempotent: re-running with the same name is a
// no-op once everything is renamed.
//
// Also exposes `rebrand(name)` for programmatic reuse from other scripts.

import { existsSync } from 'node:fs'
import { readFile, writeFile, rm } from 'node:fs/promises'
import { execSync } from 'node:child_process'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')

// Files whose "albo" is infrastructure that must survive verbatim in the
// derived project — never brand-replaced, never asserted against:
//  - .agents/**            upstream skills (pnpm run sync:skills overwrites)
//  - generated artifacts   routeTree.gen.ts, convex/_generated/**
//  - lockfile              regenerated by pnpm
//  - template machinery    their "albo" is fresh-clone detection (setup.mjs's
//                          /^albo/ guard) or the upstream remote URL
//  - README.product.md     consumed + deleted by renderProductReadme()
const SKIP = [
  /^\.agents\//,
  /(^|\/)[^/]*\.gen\.ts$/,
  /^convex\/_generated\//,
  /^pnpm-lock\.yaml$/,
  /^scripts\/(init|setup|setup-prod|upgrade-template|sync-skills)\.mjs$/,
  /^README\.product\.md$/,
]

// Binary-ish extensions we never scan as text.
const BINARY = /\.(png|jpe?g|gif|ico|webp|woff2?|ttf|otf|eot|pdf|zip)$/i

// Upstream identity tokens — masked before brand replacement, restored after,
// so the update channel keeps pointing at the starter repo.
const UPSTREAM = [
  ['albo-ouvre-boite', 'ALBO_OUVRE_BOITE'],
  ['Albo-Club', 'ALBO_CLUB'],
]

function toSlug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function toDisplay(slug) {
  return slug
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(' ')
}

function isSkipped(rel) {
  return SKIP.some((re) => re.test(rel))
}

function rebrandText(text, slug, display) {
  let out = text
  for (const [token, sentinel] of UPSTREAM) out = out.split(token).join(sentinel)
  out = out.replace(/\bAlbo\b/g, display).replace(/\balbo\b/g, slug)
  for (const [token, sentinel] of UPSTREAM) out = out.split(sentinel).join(token)
  return out
}

// Regular blobs only — drop symlinks (120000, e.g. .claude/skills/* → .agents)
// and submodules (160000) so we never try to read a directory as text.
function trackedFiles() {
  return execSync('git ls-files -s', { cwd: ROOT, encoding: 'utf8' })
    .split('\n')
    .filter(Boolean)
    .filter((line) => /^100(644|755) /.test(line))
    .map((line) => line.split('\t').slice(1).join('\t'))
}

// Swap the template-oriented README for a clean product one.
async function renderProductReadme(slug) {
  const tplPath = resolve(ROOT, 'README.product.md')
  if (!existsSync(tplPath)) return false
  const tpl = await readFile(tplPath, 'utf8')
  const readme = tpl.split('__APP_NAME__').join(slug)
  await writeFile(resolve(ROOT, 'README.md'), readme)
  await rm(tplPath)
  console.log('✓ README.md (product) + removed README.product.md')
  return true
}

// Drop the "before deriving the template" framing from CLAUDE.md so a derived
// project doesn't read like the starter.
async function detemplatizeClaudeMd() {
  const path = resolve(ROOT, 'CLAUDE.md')
  if (!existsSync(path)) return false
  const before = await readFile(path, 'utf8')
  const after = before.replace(
    'Before forking the template into a prod project, run through `TESTING.md`',
    'Before each production deployment, run through `TESTING.md`',
  )
  if (after === before) return false
  await writeFile(path, after)
  console.log('✓ CLAUDE.md')
  return true
}

// Fail loudly if any standalone brand token survived (upstream identity and
// skipped infrastructure files excluded).
async function assertNoResidualBrand() {
  const hits = []
  for (const rel of trackedFiles()) {
    if (isSkipped(rel) || BINARY.test(rel)) continue
    const path = resolve(ROOT, rel)
    if (!existsSync(path)) continue
    let text
    try {
      text = await readFile(path, 'utf8')
    } catch {
      continue
    }
    // Remove upstream identity so "albo-ouvre-boite" doesn't count as residue.
    let stripped = text
    for (const [token] of UPSTREAM) stripped = stripped.split(token).join('')
    stripped.split('\n').forEach((line, i) => {
      if (/\balbo\b/i.test(line)) hits.push(`${rel}:${i + 1}: ${line.trim()}`)
    })
  }
  if (hits.length > 0) {
    throw new Error(
      `Rebrand incomplete — ${hits.length} residual "albo" brand token(s):\n` +
        hits.map((h) => `  ${h}`).join('\n'),
    )
  }
}

/**
 * Rebrand the template in place.
 * @param {string} name raw project name (gets slugified)
 * @returns {Promise<{ slug: string, display: string, touched: number }>}
 */
export async function rebrand(name) {
  const slug = toSlug(name)
  if (slug.length < 3 || slug.length > 40) {
    throw new Error('Project name must produce a 3-40 char kebab slug.')
  }
  const display = toDisplay(slug)

  let touched = 0
  for (const rel of trackedFiles()) {
    if (rel === 'README.md' || isSkipped(rel) || BINARY.test(rel)) continue
    const path = resolve(ROOT, rel)
    const before = await readFile(path, 'utf8')
    let after = before
    if (rel === 'package.json') {
      after = after.replace(
        /"name":\s*"[^"]+"/,
        `"name": ${JSON.stringify(slug)}`,
      )
    }
    after = rebrandText(after, slug, display)
    if (after !== before) {
      await writeFile(path, after)
      touched += 1
      console.log(`✓ ${rel}`)
    }
  }

  if (await renderProductReadme(slug)) touched += 1
  if (await detemplatizeClaudeMd()) touched += 1

  await assertNoResidualBrand()

  return { slug, display, touched }
}

function usage() {
  console.error('Usage: pnpm run init <project-name> [--reset-git]')
  process.exit(1)
}

async function cli() {
  const name = process.argv[2]
  const resetGit = process.argv.includes('--reset-git')
  if (!name || name.startsWith('-')) usage()

  try {
    const { touched } = await rebrand(name)
    if (touched === 0) {
      console.log('Nothing to rename — already personalized?')
    } else {
      console.log(`Rebranded ${touched} file${touched > 1 ? 's' : ''}.`)
    }
  } catch (err) {
    console.error(err.message)
    process.exit(1)
  }

  if (resetGit) {
    console.log('Resetting git history…')
    await rm(resolve(ROOT, '.git'), { recursive: true, force: true })
    execSync('git init -b main', { cwd: ROOT, stdio: 'inherit' })
    execSync('git add -A', { cwd: ROOT, stdio: 'inherit' })
    execSync('git commit -m "chore: scaffold from albo-ouvre-boite"', {
      cwd: ROOT,
      stdio: 'inherit',
    })
    console.log('Done. Set a remote with `git remote add origin …` when ready.')
  }
}

// Run CLI only if invoked directly (not when imported).
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await cli()
}
