/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppMeRouteImport } from './routes/app/me'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AppOrgSlugRouteRouteImport } from './routes/app/$orgSlug/route'
import { Route as AppOrgSlugIndexRouteImport } from './routes/app/$orgSlug/index'
import { Route as AppOrgSlugItemsRouteImport } from './routes/app/$orgSlug/items'
import { Route as AppOrgSlugChangelogRouteImport } from './routes/app/$orgSlug/changelog'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrgSlugSettingsRouteRouteImport } from './routes/app/$orgSlug/settings/route'
import { Route as AppOrgSlugSettingsIndexRouteImport } from './routes/app/$orgSlug/settings/index'
import { Route as AppOrgSlugSettingsMembersRouteImport } from './routes/app/$orgSlug/settings/members'
import { Route as AppOrgSlugSettingsInvitationsRouteImport } from './routes/app/$orgSlug/settings/invitations'
import { Route as AppOrgSlugSettingsGeneralRouteImport } from './routes/app/$orgSlug/settings/general'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugRouteRoute = AppOrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrgSlugIndexRoute = AppOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugItemsRoute = AppOrgSlugItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugChangelogRoute = AppOrgSlugChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugSettingsRouteRoute = AppOrgSlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugSettingsIndexRoute = AppOrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugSettingsRouteRoute,
} as any)
const AppOrgSlugSettingsMembersRoute =
  AppOrgSlugSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppOrgSlugSettingsRouteRoute,
  } as any)
const AppOrgSlugSettingsInvitationsRoute =
  AppOrgSlugSettingsInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AppOrgSlugSettingsRouteRoute,
  } as any)
const AppOrgSlugSettingsGeneralRoute =
  AppOrgSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AppOrgSlugSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRoute
  '/app/me': typeof AppMeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$orgSlug/changelog': typeof AppOrgSlugChangelogRoute
  '/app/$orgSlug/items': typeof AppOrgSlugItemsRoute
  '/app/$orgSlug/': typeof AppOrgSlugIndexRoute
  '/app/$orgSlug/settings/general': typeof AppOrgSlugSettingsGeneralRoute
  '/app/$orgSlug/settings/invitations': typeof AppOrgSlugSettingsInvitationsRoute
  '/app/$orgSlug/settings/members': typeof AppOrgSlugSettingsMembersRoute
  '/app/$orgSlug/settings/': typeof AppOrgSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRoute
  '/app/me': typeof AppMeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$orgSlug/changelog': typeof AppOrgSlugChangelogRoute
  '/app/$orgSlug/items': typeof AppOrgSlugItemsRoute
  '/app/$orgSlug': typeof AppOrgSlugIndexRoute
  '/app/$orgSlug/settings/general': typeof AppOrgSlugSettingsGeneralRoute
  '/app/$orgSlug/settings/invitations': typeof AppOrgSlugSettingsInvitationsRoute
  '/app/$orgSlug/settings/members': typeof AppOrgSlugSettingsMembersRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRoute
  '/app/me': typeof AppMeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$orgSlug/changelog': typeof AppOrgSlugChangelogRoute
  '/app/$orgSlug/items': typeof AppOrgSlugItemsRoute
  '/app/$orgSlug/': typeof AppOrgSlugIndexRoute
  '/app/$orgSlug/settings/general': typeof AppOrgSlugSettingsGeneralRoute
  '/app/$orgSlug/settings/invitations': typeof AppOrgSlugSettingsInvitationsRoute
  '/app/$orgSlug/settings/members': typeof AppOrgSlugSettingsMembersRoute
  '/app/$orgSlug/settings/': typeof AppOrgSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/$orgSlug'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/onboarding'
    | '/app/'
    | '/app/$orgSlug/settings'
    | '/api/auth/$'
    | '/app/$orgSlug/changelog'
    | '/app/$orgSlug/items'
    | '/app/$orgSlug/'
    | '/app/$orgSlug/settings/general'
    | '/app/$orgSlug/settings/invitations'
    | '/app/$orgSlug/settings/members'
    | '/app/$orgSlug/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/onboarding'
    | '/app'
    | '/api/auth/$'
    | '/app/$orgSlug/changelog'
    | '/app/$orgSlug/items'
    | '/app/$orgSlug'
    | '/app/$orgSlug/settings/general'
    | '/app/$orgSlug/settings/invitations'
    | '/app/$orgSlug/settings/members'
    | '/app/$orgSlug/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/$orgSlug'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/onboarding'
    | '/app/'
    | '/app/$orgSlug/settings'
    | '/api/auth/$'
    | '/app/$orgSlug/changelog'
    | '/app/$orgSlug/items'
    | '/app/$orgSlug/'
    | '/app/$orgSlug/settings/general'
    | '/app/$orgSlug/settings/invitations'
    | '/app/$orgSlug/settings/members'
    | '/app/$orgSlug/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgSlug': {
      id: '/app/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/app/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$orgSlug/': {
      id: '/app/$orgSlug/'
      path: '/'
      fullPath: '/app/$orgSlug/'
      preLoaderRoute: typeof AppOrgSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/items': {
      id: '/app/$orgSlug/items'
      path: '/items'
      fullPath: '/app/$orgSlug/items'
      preLoaderRoute: typeof AppOrgSlugItemsRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/changelog': {
      id: '/app/$orgSlug/changelog'
      path: '/changelog'
      fullPath: '/app/$orgSlug/changelog'
      preLoaderRoute: typeof AppOrgSlugChangelogRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgSlug/settings': {
      id: '/app/$orgSlug/settings'
      path: '/settings'
      fullPath: '/app/$orgSlug/settings'
      preLoaderRoute: typeof AppOrgSlugSettingsRouteRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/settings/': {
      id: '/app/$orgSlug/settings/'
      path: '/'
      fullPath: '/app/$orgSlug/settings/'
      preLoaderRoute: typeof AppOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/settings/members': {
      id: '/app/$orgSlug/settings/members'
      path: '/members'
      fullPath: '/app/$orgSlug/settings/members'
      preLoaderRoute: typeof AppOrgSlugSettingsMembersRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/settings/invitations': {
      id: '/app/$orgSlug/settings/invitations'
      path: '/invitations'
      fullPath: '/app/$orgSlug/settings/invitations'
      preLoaderRoute: typeof AppOrgSlugSettingsInvitationsRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/settings/general': {
      id: '/app/$orgSlug/settings/general'
      path: '/general'
      fullPath: '/app/$orgSlug/settings/general'
      preLoaderRoute: typeof AppOrgSlugSettingsGeneralRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
  }
}

interface AppOrgSlugSettingsRouteRouteChildren {
  AppOrgSlugSettingsGeneralRoute: typeof AppOrgSlugSettingsGeneralRoute
  AppOrgSlugSettingsInvitationsRoute: typeof AppOrgSlugSettingsInvitationsRoute
  AppOrgSlugSettingsMembersRoute: typeof AppOrgSlugSettingsMembersRoute
  AppOrgSlugSettingsIndexRoute: typeof AppOrgSlugSettingsIndexRoute
}

const AppOrgSlugSettingsRouteRouteChildren: AppOrgSlugSettingsRouteRouteChildren =
  {
    AppOrgSlugSettingsGeneralRoute: AppOrgSlugSettingsGeneralRoute,
    AppOrgSlugSettingsInvitationsRoute: AppOrgSlugSettingsInvitationsRoute,
    AppOrgSlugSettingsMembersRoute: AppOrgSlugSettingsMembersRoute,
    AppOrgSlugSettingsIndexRoute: AppOrgSlugSettingsIndexRoute,
  }

const AppOrgSlugSettingsRouteRouteWithChildren =
  AppOrgSlugSettingsRouteRoute._addFileChildren(
    AppOrgSlugSettingsRouteRouteChildren,
  )

interface AppOrgSlugRouteRouteChildren {
  AppOrgSlugSettingsRouteRoute: typeof AppOrgSlugSettingsRouteRouteWithChildren
  AppOrgSlugChangelogRoute: typeof AppOrgSlugChangelogRoute
  AppOrgSlugItemsRoute: typeof AppOrgSlugItemsRoute
  AppOrgSlugIndexRoute: typeof AppOrgSlugIndexRoute
}

const AppOrgSlugRouteRouteChildren: AppOrgSlugRouteRouteChildren = {
  AppOrgSlugSettingsRouteRoute: AppOrgSlugSettingsRouteRouteWithChildren,
  AppOrgSlugChangelogRoute: AppOrgSlugChangelogRoute,
  AppOrgSlugItemsRoute: AppOrgSlugItemsRoute,
  AppOrgSlugIndexRoute: AppOrgSlugIndexRoute,
}

const AppOrgSlugRouteRouteWithChildren = AppOrgSlugRouteRoute._addFileChildren(
  AppOrgSlugRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppOrgSlugRouteRoute: typeof AppOrgSlugRouteRouteWithChildren
  AppAdminRoute: typeof AppAdminRoute
  AppMeRoute: typeof AppMeRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOrgSlugRouteRoute: AppOrgSlugRouteRouteWithChildren,
  AppAdminRoute: AppAdminRoute,
  AppMeRoute: AppMeRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
